
-- Old customer/staff/owner tables used the 3-value user_role enum itself as their
-- primary key, so each could only ever hold 3 rows total. profiles + role replaces
-- them. All 7 old tables are empty, so this is a safe rebuild, not a data migration.
drop table if exists public.customer cascade;
drop table if exists public.staff cascade;
drop table if exists public.owner cascade;
drop table if exists public.booking cascade;
drop table if exists public.walk_in_booking cascade;
drop table if exists public.payment cascade;
drop table if exists public.assets cascade;

create table public.payment (
  payment_id bigint generated by default as identity primary key,
  cost numeric(10,2) not null default 0,
  paid numeric(10,2) not null default 0,
  payment_method text,
  down_full text check (down_full in ('downpayment','full')),
  created_at timestamptz not null default now()
);
comment on table public.payment is 'payment table';

create table public.assets (
  assets_id bigint generated by default as identity primary key,
  category text,
  file_name text,
  location text,
  created_at timestamptz not null default now()
);
comment on table public.assets is 'assets table (court/featured images etc.)';

create table public.booking (
  booking_id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  sports text not null,
  courts text not null,
  time_date timestamptz not null,
  payment_id bigint references public.payment(payment_id),
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled','completed')),
  created_at timestamptz not null default now()
);
comment on table public.booking is 'booking table';
create index idx_booking_customer_id on public.booking(customer_id);

create table public.walk_in_booking (
  walkin_id bigint generated by default as identity primary key,
  staff_id uuid references public.profiles(id) on delete set null,
  sports text not null,
  courts text not null,
  time_date timestamptz not null,
  payment_id bigint references public.payment(payment_id),
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled','completed')),
  created_at timestamptz not null default now()
);
comment on table public.walk_in_booking is 'walk-in booking table';
create index idx_walk_in_booking_staff_id on public.walk_in_booking(staff_id);

alter table public.payment enable row level security;
alter table public.assets enable row level security;
alter table public.booking enable row level security;
alter table public.walk_in_booking enable row level security;
